### ISSUE TITLE
Any chance for a binary?

### ISSUE THREAD

**Issue by for-coursera** [stig/Desdemona#1]
As you surely know, links to DMGs are broken... Any chance you will release an executable? :)

**Comment by stig** [comment]
I'm afraid not. It's been 9 years since I last touched this codebase (except the README) and I haven't been set up to do OS X development in several years. (Even if I did release binaries, you probably wouldn't be able to install them because of gatekeeper.) But the source is available and you are welcome to make your own!

**Comment by for-coursera** [comment]
OK, thanks for the details.
